### ISSUE TITLE
Knative: Use explicit revision names for blue/green instead latestRevision

### ISSUE THREAD

**Issue by timosalm** [tsalm-pivotal/tap-blue-green-canary#1]
```
spec:
  traffic:
  - latestRevision: true
    tag: canary
  - revisionName: <new-rev>
    percent: 25
    tag: blue
  - revisionName: <old-rev>
    percent: 75
    tag: green
```
